### ISSUE TITLE
Download RSL tar.gz no longer works in conda-build

### ISSUE THREAD

**Issue by jjhelmus** [conda-forge/trmm_rsl-feedstock#5]
conda-build no long seems to be able to download the RSL tar.gz file from the FTP site, for example [a recent Travis build](https://travis-ci.org/conda-forge/trmm_rsl-feedstock/builds/126377175).  It appears as if the FTP server is blocking non-browser based downloads.  I can download the tar.gz file using Chrome but the same link fails with wget.

We could mirror the tarball somewhere (in the GitHub repo?) and point the recipe to that locations although I am not really happy with the solution.

**Comment by kmuehlbauer** [comment]
@jjhelmus have you tried `wget` with the `--referer`, `--user-agent` and `--header` switches? So `wget` pretends to be a real browser.

**Comment by jjhelmus** [comment]
The issue is that conda build needs to download the file, not wget.  I'm think mirroring the source is a better option that messing downloading the source inside the recipe or mucking with the way conda build performs the download.
